import type { SourceAttribution } from './types.js';

export interface SourceInput {
  readonly toolsUsed: readonly string[];
  readonly hasMemoryRecall: boolean;
  readonly hasKnowledgeGraph: boolean;
  readonly hasUserData: boolean;
}

const HEDGE_PHRASES = [
  'i think', 'i believe', "i'm not sure", "i'm not entirely sure",
  'it might be', 'it could be', 'probably', 'possibly', 'if i recall',
  'i may be wrong', 'not certain',
];

export function attributeSources(input: SourceInput): SourceAttribution[] {
  const sources: SourceAttribution[] = [];

  for (const tool of input.toolsUsed) {
    sources.push({ type: 'tool_result', label: `Tool: ${tool}`, confidence: 0.95 });
  }

  if (input.hasMemoryRecall) {
    sources.push({ type: 'memory_recall', label: 'Similar past conversation', confidence: 0.72 });
  }

  if (input.hasKnowledgeGraph) {
    sources.push({ type: 'knowledge_graph', label: 'Knowledge graph lookup', confidence: 0.85 });
  }

  if (input.hasUserData) {
    sources.push({ type: 'user_data', label: 'User preferences and history', confidence: 0.80 });
  }

  // Always add model generation as the base source
  sources.push({
    type: 'model_generation',
    label: sources.length > 0 ? 'Synthesized from above sources' : 'Generated by model',
    confidence: 0.7,
  });

  return sources;
}

export function countHedgePhrases(text: string): number {
  if (!text) return 0;
  const lower = text.toLowerCase();
  let count = 0;
  for (const phrase of HEDGE_PHRASES) {
    let idx = 0;
    while ((idx = lower.indexOf(phrase, idx)) !== -1) {
      count++;
      idx += phrase.length;
    }
  }
  return count;
}
