export { TheArchitect, createArchitect } from './the-architect/index.js';
export { ARCHITECT_BASE_PROMPT } from './the-architect/system-prompt.js';
export { CONTEXT_PROFILES } from './the-architect/context-profiles.js';
export { SOURCE_MAP } from './the-architect/source-map.js';
export { TRAIT_TO_INSTRUCTION } from './the-architect/trait-to-instruction.js';
export { detectContext, scoreAllDomains } from './the-architect/context-detector.js';
export { assemblePromptModifier, getActiveSources } from './the-architect/prompt-assembler.js';
export { EMOTIONAL_OVERRIDES, applyEmotionalOverride } from './the-architect/emotional-overrides.js';
export type { TraitMix, TraitValue, TaskContext, TraitSource, ContextDomain, EmotionalRegister, ContextSignal, PromptOutput, } from './schema.js';
export { CorrectionStore } from './the-architect/correction-store.js';
export type { DetectionCorrection, CorrectionPattern } from './the-architect/correction-store.js';
export { InMemoryEncryptedStorage, VaultStorageAdapter } from './the-architect/persistence-adapter.js';
export type { EncryptedStorage, VaultLike } from './the-architect/persistence-adapter.js';
export { ArchitectPersistence } from './the-architect/persistence.js';
export type { ArchitectPreferences } from './the-architect/persistence.js';
export { ContextRecommender } from './the-architect/recommender.js';
export type { ContextRecommendation } from './the-architect/recommender.js';
export { ConversationContext } from './the-architect/conversation-context.js';
export type { ConversationSummary, ConversationState, DetectionRecord } from './the-architect/conversation-context.js';
export { EmotionalTracker, estimateIntensity } from './the-architect/emotional-tracker.js';
export type { EmotionalTrajectory, EffectiveEmotion } from './the-architect/emotional-tracker.js';
export { CustomWeights, WEIGHT_PRESETS } from './the-architect/custom-weights.js';
export type { WeightPreset } from './the-architect/custom-weights.js';
export { ConversationExporter } from './the-architect/conversation-export.js';
export type { ChatMessage, AssistantMetadata, ExportedMessage, ExportedConversation } from './the-architect/conversation-export.js';
//# sourceMappingURL=index.d.ts.map