import { getLogger } from '@auxiora/logger';

const logger = getLogger('runtime:response-provenance');

export interface ProvenanceEntry {
  /** Unique response ID */
  responseId: string;
  /** Session ID */
  sessionId: string;
  /** Timestamp */
  timestamp: number;
  /** Memory IDs that were retrieved for context */
  memoryIds: string[];
  /** Context signals that influenced the response */
  contextSignals: ContextSignalRecord[];
  /** Tools that were called during response generation */
  toolCalls: ToolCallRecord[];
  /** Enrichment stages that ran */
  enrichmentStages: string[];
  /** Model and provider used */
  model: { provider: string; model: string };
  /** Token usage */
  tokenUsage: { input: number; output: number };
}

export interface ContextSignalRecord {
  name: string;
  type: string;
  value: string;
  confidence?: number;
}

export interface ToolCallRecord {
  toolName: string;
  durationMs: number;
  success: boolean;
}

export interface ProvenanceSummary {
  /** Human-readable explanation of where the response came from */
  explanation: string;
  /** List of contributing sources */
  sources: Array<{ type: string; label: string; detail?: string }>;
  /** Whether the response was grounded in user data */
  groundedInUserData: boolean;
  /** Whether external tools/searches were used */
  usedExternalSources: boolean;
}

export class ResponseProvenanceTracker {
  private entries = new Map<string, ProvenanceEntry>();
  private maxEntries: number;

  constructor(maxEntries = 500) {
    this.maxEntries = maxEntries;
  }

  /** Record provenance for a response */
  record(entry: ProvenanceEntry): void {
    // Enforce max size
    if (this.entries.size >= this.maxEntries) {
      const oldest = this.findOldest();
      if (oldest) this.entries.delete(oldest);
    }

    this.entries.set(entry.responseId, entry);
    logger.debug('Provenance recorded', {
      responseId: entry.responseId,
      memoryCount: entry.memoryIds.length,
      toolCount: entry.toolCalls.length,
    });
  }

  /** Get provenance for a specific response */
  get(responseId: string): ProvenanceEntry | undefined {
    return this.entries.get(responseId);
  }

  /** Get a human-readable summary explaining why a response was generated */
  explain(responseId: string): ProvenanceSummary | undefined {
    const entry = this.entries.get(responseId);
    if (!entry) return undefined;

    const sources: ProvenanceSummary['sources'] = [];
    const parts: string[] = [];

    // Memories
    if (entry.memoryIds.length > 0) {
      sources.push({
        type: 'memory',
        label: `${entry.memoryIds.length} memories`,
        detail: entry.memoryIds.join(', '),
      });
      parts.push(`${entry.memoryIds.length} stored memories`);
    }

    // Context signals
    if (entry.contextSignals.length > 0) {
      for (const signal of entry.contextSignals) {
        sources.push({
          type: 'context_signal',
          label: signal.name,
          detail: signal.value,
        });
      }
      parts.push(`${entry.contextSignals.length} context signals`);
    }

    // Tools
    if (entry.toolCalls.length > 0) {
      for (const tool of entry.toolCalls) {
        sources.push({
          type: 'tool',
          label: tool.toolName,
          detail: tool.success ? `completed in ${tool.durationMs}ms` : 'failed',
        });
      }
      parts.push(`${entry.toolCalls.length} tool calls`);
    }

    // Enrichment
    if (entry.enrichmentStages.length > 0) {
      sources.push({
        type: 'enrichment',
        label: `${entry.enrichmentStages.length} enrichment stages`,
        detail: entry.enrichmentStages.join(', '),
      });
    }

    // Model
    sources.push({
      type: 'model',
      label: `${entry.model.provider}/${entry.model.model}`,
    });

    const groundedInUserData = entry.memoryIds.length > 0 || entry.contextSignals.length > 0;
    const usedExternalSources = entry.toolCalls.some(t =>
      t.toolName.includes('search') || t.toolName.includes('web') || t.toolName.includes('fetch'),
    );

    const explanation = parts.length > 0
      ? `This response was informed by ${parts.join(', ')}, processed through ${entry.enrichmentStages.length} enrichment stages, and generated by ${entry.model.provider}/${entry.model.model}.`
      : `This response was generated by ${entry.model.provider}/${entry.model.model} without specific user data.`;

    return { explanation, sources, groundedInUserData, usedExternalSources };
  }

  /** List recent response IDs for a session */
  listBySession(sessionId: string, limit = 20): string[] {
    const ids: string[] = [];
    for (const [id, entry] of this.entries) {
      if (entry.sessionId === sessionId) ids.push(id);
    }
    return ids.slice(-limit);
  }

  /** Get count of tracked responses */
  get size(): number {
    return this.entries.size;
  }

  /** Clear all entries */
  clear(): void {
    this.entries.clear();
  }

  private findOldest(): string | undefined {
    let oldestId: string | undefined;
    let oldestTime = Infinity;
    for (const [id, entry] of this.entries) {
      if (entry.timestamp < oldestTime) {
        oldestTime = entry.timestamp;
        oldestId = id;
      }
    }
    return oldestId;
  }
}
