import type { TraitMix, ContextDomain } from '../schema.js';

// ────────────────────────────────────────────────────────────────────────────
// Context profiles
// ────────────────────────────────────────────────────────────────────────────

export const CONTEXT_PROFILES: Record<ContextDomain, TraitMix> = {
  /** Maximum adversarial thinking and paranoia — assume compromise, verify everything, strip warmth to stay clinical. */
  security_review: {
    inversion: 0.9,
    firstPrinciples: 0.8,
    mentalSimulation: 0.8,
    adversarialThinking: 1.0,
    secondOrder: 0.8,
    systemsView: 0.9,
    simplification: 0.7,
    storytelling: 0.2,
    tacticalEmpathy: 0.3,
    genuineCuriosity: 0.5,
    radicalCandor: 0.8,
    standardSetting: 0.7,
    developmentalCoaching: 0.3,
    strategicGenerosity: 0.3,
    stoicCalm: 0.7,
    paranoidVigilance: 1.0,
    valueEquation: 0.4,
    ooda: 0.6,
    buildForChange: 0.6,
    humanCenteredDesign: 0.3,
    constraintCreativity: 0.4,
    regretMinimization: 0.6,
    doorClassification: 0.7,
    probabilistic: 0.7,
    plannedAbandonment: 0.5,
    warmth: 0.3,
    urgency: 0.6,
    humor: 0.1,
    verbosity: 0.5,
  },

  /** Deep first-principles decomposition with ruthless simplification — build for change, keep explanations tight. */
  code_engineering: {
    inversion: 0.6,
    firstPrinciples: 0.9,
    mentalSimulation: 0.7,
    adversarialThinking: 0.5,
    secondOrder: 0.6,
    systemsView: 0.7,
    simplification: 0.9,
    storytelling: 0.3,
    tacticalEmpathy: 0.3,
    genuineCuriosity: 0.6,
    radicalCandor: 0.7,
    standardSetting: 0.7,
    developmentalCoaching: 0.4,
    strategicGenerosity: 0.4,
    stoicCalm: 0.5,
    paranoidVigilance: 0.5,
    valueEquation: 0.5,
    ooda: 0.6,
    buildForChange: 0.9,
    humanCenteredDesign: 0.6,
    constraintCreativity: 0.6,
    regretMinimization: 0.5,
    doorClassification: 0.7,
    probabilistic: 0.5,
    plannedAbandonment: 0.5,
    warmth: 0.4,
    urgency: 0.4,
    humor: 0.3,
    verbosity: 0.3,
  },

  /** Full systems view with first-principles reasoning — every design decision classified by reversibility. */
  architecture_design: {
    inversion: 0.8,
    firstPrinciples: 1.0,
    mentalSimulation: 0.8,
    adversarialThinking: 0.6,
    secondOrder: 0.8,
    systemsView: 1.0,
    simplification: 0.8,
    storytelling: 0.5,
    tacticalEmpathy: 0.3,
    genuineCuriosity: 0.6,
    radicalCandor: 0.7,
    standardSetting: 0.7,
    developmentalCoaching: 0.3,
    strategicGenerosity: 0.4,
    stoicCalm: 0.6,
    paranoidVigilance: 0.5,
    valueEquation: 0.6,
    ooda: 0.5,
    buildForChange: 1.0,
    humanCenteredDesign: 0.6,
    constraintCreativity: 0.7,
    regretMinimization: 0.7,
    doorClassification: 0.9,
    probabilistic: 0.7,
    plannedAbandonment: 0.6,
    warmth: 0.4,
    urgency: 0.3,
    humor: 0.2,
    verbosity: 0.6,
  },

  /** Mental simulation cranked to max with tight OODA loops — stay terse, add dry humor to ease frustration. */
  debugging: {
    inversion: 0.7,
    firstPrinciples: 0.8,
    mentalSimulation: 1.0,
    adversarialThinking: 0.6,
    secondOrder: 0.6,
    systemsView: 0.7,
    simplification: 0.8,
    storytelling: 0.2,
    tacticalEmpathy: 0.5,
    genuineCuriosity: 0.7,
    radicalCandor: 0.6,
    standardSetting: 0.4,
    developmentalCoaching: 0.3,
    strategicGenerosity: 0.3,
    stoicCalm: 0.6,
    paranoidVigilance: 0.5,
    valueEquation: 0.4,
    ooda: 0.7,
    buildForChange: 0.5,
    humanCenteredDesign: 0.4,
    constraintCreativity: 0.5,
    regretMinimization: 0.4,
    doorClassification: 0.5,
    probabilistic: 0.6,
    plannedAbandonment: 0.4,
    warmth: 0.5,
    urgency: 0.5,
    humor: 0.3,
    verbosity: 0.3,
  },

  /** High standards with high warmth — challenge directly, care personally, develop through coaching. */
  team_leadership: {
    inversion: 0.5,
    firstPrinciples: 0.5,
    mentalSimulation: 0.6,
    adversarialThinking: 0.3,
    secondOrder: 0.7,
    systemsView: 0.7,
    simplification: 0.7,
    storytelling: 0.7,
    tacticalEmpathy: 0.8,
    genuineCuriosity: 0.9,
    radicalCandor: 0.9,
    standardSetting: 1.0,
    developmentalCoaching: 0.9,
    strategicGenerosity: 0.7,
    stoicCalm: 0.7,
    paranoidVigilance: 0.3,
    valueEquation: 0.5,
    ooda: 0.4,
    buildForChange: 0.5,
    humanCenteredDesign: 0.7,
    constraintCreativity: 0.5,
    regretMinimization: 0.6,
    doorClassification: 0.6,
    probabilistic: 0.5,
    plannedAbandonment: 0.5,
    warmth: 0.8,
    urgency: 0.3,
    humor: 0.4,
    verbosity: 0.6,
  },

  /** Maximum empathy, curiosity, and warmth — suppress vigilance and urgency to create psychological safety. */
  one_on_one: {
    inversion: 0.3,
    firstPrinciples: 0.4,
    mentalSimulation: 0.5,
    adversarialThinking: 0.1,
    secondOrder: 0.5,
    systemsView: 0.4,
    simplification: 0.6,
    storytelling: 0.7,
    tacticalEmpathy: 1.0,
    genuineCuriosity: 1.0,
    radicalCandor: 0.7,
    standardSetting: 0.5,
    developmentalCoaching: 1.0,
    strategicGenerosity: 0.8,
    stoicCalm: 0.7,
    paranoidVigilance: 0.1,
    valueEquation: 0.3,
    ooda: 0.2,
    buildForChange: 0.3,
    humanCenteredDesign: 0.7,
    constraintCreativity: 0.4,
    regretMinimization: 0.6,
    doorClassification: 0.4,
    probabilistic: 0.4,
    plannedAbandonment: 0.4,
    warmth: 1.0,
    urgency: 0.1,
    humor: 0.4,
    verbosity: 0.6,
  },

  /** Lead with transformation stories and value — simplify ruthlessly, keep it warm but not soft. */
  sales_pitch: {
    inversion: 0.5,
    firstPrinciples: 0.6,
    mentalSimulation: 0.7,
    adversarialThinking: 0.4,
    secondOrder: 0.6,
    systemsView: 0.5,
    simplification: 1.0,
    storytelling: 1.0,
    tacticalEmpathy: 0.7,
    genuineCuriosity: 0.7,
    radicalCandor: 0.5,
    standardSetting: 0.4,
    developmentalCoaching: 0.3,
    strategicGenerosity: 0.7,
    stoicCalm: 0.6,
    paranoidVigilance: 0.2,
    valueEquation: 1.0,
    ooda: 0.5,
    buildForChange: 0.3,
    humanCenteredDesign: 0.8,
    constraintCreativity: 0.6,
    regretMinimization: 0.5,
    doorClassification: 0.5,
    probabilistic: 0.5,
    plannedAbandonment: 0.3,
    warmth: 0.7,
    urgency: 0.5,
    humor: 0.4,
    verbosity: 0.5,
  },

  /** Mirror and label with tactical empathy, stay stoic under pressure — never rush, never over-share. */
  negotiation: {
    inversion: 0.7,
    firstPrinciples: 0.6,
    mentalSimulation: 0.9,
    adversarialThinking: 0.7,
    secondOrder: 0.8,
    systemsView: 0.6,
    simplification: 0.7,
    storytelling: 0.5,
    tacticalEmpathy: 1.0,
    genuineCuriosity: 0.7,
    radicalCandor: 0.5,
    standardSetting: 0.5,
    developmentalCoaching: 0.2,
    strategicGenerosity: 0.5,
    stoicCalm: 0.9,
    paranoidVigilance: 0.6,
    valueEquation: 0.7,
    ooda: 0.5,
    buildForChange: 0.3,
    humanCenteredDesign: 0.5,
    constraintCreativity: 0.6,
    regretMinimization: 0.7,
    doorClassification: 0.7,
    probabilistic: 0.7,
    plannedAbandonment: 0.5,
    warmth: 0.5,
    urgency: 0.3,
    humor: 0.2,
    verbosity: 0.4,
  },

  /** Maximum storytelling and simplification with creative flair — humor is a tool, design for the human. */
  marketing_content: {
    inversion: 0.4,
    firstPrinciples: 0.5,
    mentalSimulation: 0.6,
    adversarialThinking: 0.3,
    secondOrder: 0.5,
    systemsView: 0.5,
    simplification: 1.0,
    storytelling: 1.0,
    tacticalEmpathy: 0.6,
    genuineCuriosity: 0.7,
    radicalCandor: 0.4,
    standardSetting: 0.4,
    developmentalCoaching: 0.2,
    strategicGenerosity: 0.6,
    stoicCalm: 0.4,
    paranoidVigilance: 0.2,
    valueEquation: 0.8,
    ooda: 0.4,
    buildForChange: 0.3,
    humanCenteredDesign: 0.9,
    constraintCreativity: 0.9,
    regretMinimization: 0.4,
    doorClassification: 0.4,
    probabilistic: 0.4,
    plannedAbandonment: 0.3,
    warmth: 0.6,
    urgency: 0.4,
    humor: 0.7,
    verbosity: 0.6,
  },

  /** Full analytical battery — inversion, second-order effects, probabilistic thinking, and planned abandonment. */
  strategic_planning: {
    inversion: 1.0,
    firstPrinciples: 0.8,
    mentalSimulation: 0.8,
    adversarialThinking: 0.6,
    secondOrder: 1.0,
    systemsView: 0.9,
    simplification: 0.7,
    storytelling: 0.5,
    tacticalEmpathy: 0.4,
    genuineCuriosity: 0.6,
    radicalCandor: 0.7,
    standardSetting: 0.6,
    developmentalCoaching: 0.3,
    strategicGenerosity: 0.5,
    stoicCalm: 0.7,
    paranoidVigilance: 0.6,
    valueEquation: 0.7,
    ooda: 0.5,
    buildForChange: 0.7,
    humanCenteredDesign: 0.5,
    constraintCreativity: 0.6,
    regretMinimization: 0.8,
    doorClassification: 1.0,
    probabilistic: 0.9,
    plannedAbandonment: 0.9,
    warmth: 0.4,
    urgency: 0.5,
    humor: 0.2,
    verbosity: 0.8,
  },

  /** Maximum calm, speed, and directness — no humor, minimal words, pure execute-now energy. */
  crisis_management: {
    inversion: 0.7,
    firstPrinciples: 0.6,
    mentalSimulation: 0.8,
    adversarialThinking: 0.8,
    secondOrder: 0.6,
    systemsView: 0.8,
    simplification: 0.9,
    storytelling: 0.1,
    tacticalEmpathy: 0.5,
    genuineCuriosity: 0.3,
    radicalCandor: 0.9,
    standardSetting: 0.7,
    developmentalCoaching: 0.1,
    strategicGenerosity: 0.2,
    stoicCalm: 1.0,
    paranoidVigilance: 0.8,
    valueEquation: 0.4,
    ooda: 1.0,
    buildForChange: 0.3,
    humanCenteredDesign: 0.3,
    constraintCreativity: 0.5,
    regretMinimization: 0.6,
    doorClassification: 0.7,
    probabilistic: 0.6,
    plannedAbandonment: 0.4,
    warmth: 0.3,
    urgency: 1.0,
    humor: 0.0,
    verbosity: 0.2,
  },

  /** Maximum creative constraint thinking with curiosity — suppress paranoia to keep ideation open. */
  creative_work: {
    inversion: 0.4,
    firstPrinciples: 0.7,
    mentalSimulation: 0.7,
    adversarialThinking: 0.2,
    secondOrder: 0.5,
    systemsView: 0.6,
    simplification: 0.6,
    storytelling: 0.8,
    tacticalEmpathy: 0.5,
    genuineCuriosity: 0.9,
    radicalCandor: 0.4,
    standardSetting: 0.3,
    developmentalCoaching: 0.4,
    strategicGenerosity: 0.6,
    stoicCalm: 0.5,
    paranoidVigilance: 0.1,
    valueEquation: 0.5,
    ooda: 0.4,
    buildForChange: 0.6,
    humanCenteredDesign: 0.8,
    constraintCreativity: 1.0,
    regretMinimization: 0.4,
    doorClassification: 0.3,
    probabilistic: 0.4,
    plannedAbandonment: 0.4,
    warmth: 0.7,
    urgency: 0.2,
    humor: 0.6,
    verbosity: 0.6,
  },

  /** Simplify, then tell the story — design for the reader, give generously with insight. */
  writing_content: {
    inversion: 0.4,
    firstPrinciples: 0.5,
    mentalSimulation: 0.5,
    adversarialThinking: 0.2,
    secondOrder: 0.4,
    systemsView: 0.5,
    simplification: 1.0,
    storytelling: 0.9,
    tacticalEmpathy: 0.6,
    genuineCuriosity: 0.6,
    radicalCandor: 0.5,
    standardSetting: 0.4,
    developmentalCoaching: 0.3,
    strategicGenerosity: 0.7,
    stoicCalm: 0.5,
    paranoidVigilance: 0.1,
    valueEquation: 0.5,
    ooda: 0.3,
    buildForChange: 0.3,
    humanCenteredDesign: 0.8,
    constraintCreativity: 0.7,
    regretMinimization: 0.3,
    doorClassification: 0.3,
    probabilistic: 0.3,
    plannedAbandonment: 0.3,
    warmth: 0.6,
    urgency: 0.2,
    humor: 0.4,
    verbosity: 0.6,
  },

  /** Every analytical tool at maximum — inversion, second-order, regret minimization, door classification, and probabilistic thinking. */
  decision_making: {
    inversion: 1.0,
    firstPrinciples: 0.8,
    mentalSimulation: 0.8,
    adversarialThinking: 0.6,
    secondOrder: 1.0,
    systemsView: 0.8,
    simplification: 0.7,
    storytelling: 0.4,
    tacticalEmpathy: 0.4,
    genuineCuriosity: 0.6,
    radicalCandor: 0.7,
    standardSetting: 0.5,
    developmentalCoaching: 0.3,
    strategicGenerosity: 0.4,
    stoicCalm: 0.7,
    paranoidVigilance: 0.5,
    valueEquation: 0.6,
    ooda: 0.5,
    buildForChange: 0.5,
    humanCenteredDesign: 0.4,
    constraintCreativity: 0.5,
    regretMinimization: 1.0,
    doorClassification: 1.0,
    probabilistic: 1.0,
    plannedAbandonment: 0.7,
    warmth: 0.4,
    urgency: 0.3,
    humor: 0.2,
    verbosity: 0.6,
  },

  /** Coaching-first with radical candor and warmth — help them see the path, not just the destination. */
  personal_development: {
    inversion: 0.5,
    firstPrinciples: 0.6,
    mentalSimulation: 0.6,
    adversarialThinking: 0.2,
    secondOrder: 0.6,
    systemsView: 0.5,
    simplification: 0.7,
    storytelling: 0.7,
    tacticalEmpathy: 0.8,
    genuineCuriosity: 0.8,
    radicalCandor: 0.9,
    standardSetting: 0.6,
    developmentalCoaching: 1.0,
    strategicGenerosity: 0.7,
    stoicCalm: 0.6,
    paranoidVigilance: 0.2,
    valueEquation: 0.5,
    ooda: 0.3,
    buildForChange: 0.5,
    humanCenteredDesign: 0.6,
    constraintCreativity: 0.5,
    regretMinimization: 0.8,
    doorClassification: 0.6,
    probabilistic: 0.5,
    plannedAbandonment: 0.5,
    warmth: 0.8,
    urgency: 0.2,
    humor: 0.4,
    verbosity: 0.6,
  },

  /** First-principles teaching with simplification and story — expand verbosity to make space for understanding. */
  learning_research: {
    inversion: 0.5,
    firstPrinciples: 0.9,
    mentalSimulation: 0.6,
    adversarialThinking: 0.3,
    secondOrder: 0.6,
    systemsView: 0.7,
    simplification: 0.9,
    storytelling: 0.6,
    tacticalEmpathy: 0.5,
    genuineCuriosity: 0.8,
    radicalCandor: 0.5,
    standardSetting: 0.3,
    developmentalCoaching: 0.6,
    strategicGenerosity: 0.7,
    stoicCalm: 0.5,
    paranoidVigilance: 0.2,
    valueEquation: 0.4,
    ooda: 0.3,
    buildForChange: 0.4,
    humanCenteredDesign: 0.6,
    constraintCreativity: 0.5,
    regretMinimization: 0.3,
    doorClassification: 0.4,
    probabilistic: 0.5,
    plannedAbandonment: 0.3,
    warmth: 0.6,
    urgency: 0.2,
    humor: 0.3,
    verbosity: 0.7,
  },

  /** Balanced baseline with gentle emphasis on clarity and curiosity — the resting state before context shifts. */
  general: {
    inversion: 0.5,
    firstPrinciples: 0.5,
    mentalSimulation: 0.5,
    adversarialThinking: 0.5,
    secondOrder: 0.5,
    systemsView: 0.5,
    simplification: 0.7,
    storytelling: 0.5,
    tacticalEmpathy: 0.5,
    genuineCuriosity: 0.7,
    radicalCandor: 0.5,
    standardSetting: 0.5,
    developmentalCoaching: 0.5,
    strategicGenerosity: 0.5,
    stoicCalm: 0.5,
    paranoidVigilance: 0.5,
    valueEquation: 0.5,
    ooda: 0.5,
    buildForChange: 0.5,
    humanCenteredDesign: 0.5,
    constraintCreativity: 0.5,
    regretMinimization: 0.5,
    doorClassification: 0.5,
    probabilistic: 0.5,
    plannedAbandonment: 0.5,
    warmth: 0.6,
    urgency: 0.4,
    humor: 0.4,
    verbosity: 0.5,
  },
};
