import { describe, it, expect } from 'vitest';
import type {
  TransparencyMeta,
  ConfidenceFactor,
  SourceAttribution,
  ConfidenceLevel,
} from '../types.js';

describe('TransparencyMeta types', () => {
  it('accepts a valid TransparencyMeta object', () => {
    const meta: TransparencyMeta = {
      confidence: {
        level: 'high',
        score: 0.87,
        factors: [
          { signal: 'tool_grounded', impact: 'positive', detail: 'Response used tool output' },
        ],
      },
      sources: [
        { type: 'tool_result', label: 'Web search', confidence: 0.95 },
        { type: 'model_generation', label: 'Generated by model', confidence: 0.7 },
      ],
      model: {
        provider: 'anthropic',
        model: 'claude-3.5-sonnet',
        tokens: { input: 156, output: 278 },
        cost: { input: 0.0012, output: 0.0028, total: 0.004 },
        finishReason: 'stop',
        latencyMs: 1247,
      },
      personality: {
        domain: 'code_engineering',
        emotionalRegister: 'neutral',
        activeTraits: [{ name: 'precise', weight: 0.82 }],
      },
      trace: {
        enrichmentStages: ['memory', 'mode', 'architect', 'self-awareness', 'model-identity'],
        toolsUsed: ['web_search'],
        processingMs: 1500,
      },
    };
    expect(meta.confidence.level).toBe('high');
    expect(meta.sources).toHaveLength(2);
    expect(meta.model.cost.total).toBe(0.004);
  });

  it('allows optional knowledgeBoundary in personality', () => {
    const meta: TransparencyMeta = {
      confidence: { level: 'low', score: 0.35, factors: [] },
      sources: [],
      model: {
        provider: 'anthropic',
        model: 'claude-3.5-sonnet',
        tokens: { input: 100, output: 200 },
        cost: { input: 0.001, output: 0.002, total: 0.003 },
        finishReason: 'stop',
        latencyMs: 800,
      },
      personality: {
        domain: 'general',
        emotionalRegister: 'uncertain',
        activeTraits: [],
        knowledgeBoundary: { topic: 'kubernetes networking', corrections: 2 },
      },
      trace: { enrichmentStages: [], toolsUsed: [], processingMs: 500 },
    };
    expect(meta.personality.knowledgeBoundary?.corrections).toBe(2);
  });
});
